FROM node:12 as builder
WORKDIR /app
COPY ./package*.json ./

RUN apt-get update
RUN apt install yarn -y
RUN yarn install
COPY . .
CMD ["yarn", "run", "build"]

# ------------------------------------------------------
# Production Build
# ------------------------------------------------------

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]