version: '3.1'

networks:
    app-tier:
        driver: bridge
services:
    mysql:
        networks:
            - app-tier
        image: mysql:5.7
        container_name: dku-sms-database
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dku-sms
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    app:
        networks:
            - app-tier
        container_name: dku-sms-backend
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
        restart: always
        ports:
            - '80:4000'
        links:
            - mysql
        depends_on:
            - mysql
